### ISSUE TITLE
Migrate to Github

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/grove-spring-boot#1]
It has matured enough to migrate to Github

- check and resolve pending PR's
- import from internal bitbucket to github
- add deprecation message to bitbucket
- migrate unresolved PR's
- prune unnecessary branches
- fix README, package*, NOTICE/LICENSE
- publish under `@marklogic-community`

**Comment by grtjn** [comment]
Github Import feature: https://github.com/marklogic-community/grove-spring-boot/import

Use the bitbucket git url (the one from `git remote -v`), works like a charm..

**Comment by sashamitrovich** [comment]
I'm on it.

**Comment by sashamitrovich** [comment]
Done.

**Comment by sashamitrovich** [comment]
@paxtonhare, there are 2 more branches after importing the project. Can they be pruned?
